<?php
/**
 * AMS Cache - Uninstall option.
 *
 * @author Terry Lin
 * @link https://terryl.in/
 * @since 1.0.0
 * @version 1.0.0
 */

if ( ! defined( 'SCM_INC' ) ) {
	die;
}

$option_uninstall = get_option( 'scm_option_uninstall', 'yes' );

?>

<div>
	<div class="scm-option-item">
		<input type="radio" name="scm_option_uninstall" id="ams-cache-uninstall-option-yes" value="yes" 
			<?php checked( $option_uninstall, 'yes' ); ?>>
		<label for="ams-cache-uninstall-option-yes">
			<?php _e( 'Remove data generated by AMS Cache.', 'ams-cache' ); ?><br />
		<label>
	</div>
	<div class="scm-option-item">
		<input type="radio" name="scm_option_uninstall" id="ams-cache-uninstall-option-no" value="no" 
			<?php checked( $option_uninstall, 'no' ); ?>>
		<label for="ams-cache-uninstall-option-no">
			<?php _e( 'Keep data generated by AMS Cache.', 'ams-cache' ); ?>
		<label>
	</div>	
</div>
<p><em><?php _e( 'This option only works when you uninstall this plugin.', 'ams-cache' ); ?></em></p>
